/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as presaleSol from "./Presale.sol";
export type { presaleSol };
export type { Holdings } from "./Holdings";
